name: vehicle_gallery
description: A Flutter application for viewing vehicle images and videos with iOS-like interface
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  photo_view: ^0.14.0
  video_player: ^2.8.1
  flutter_staggered_grid_view: ^0.7.0
  cached_network_image: ^3.3.0
  flutter_svg: ^2.0.9
  path_provider: ^2.1.1
  permission_handler: ^11.0.1
  image_picker: ^1.0.4
  file_picker: ^6.1.1
  sqflite: ^2.3.0
  share_plus: ^7.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/

# flutter_icons:
#   android: "launcher_icon"  
#   ios: true
#   image_path: "assets/icons/app_icon.png"
#   min_sdk_android: 21